version: "3.9"

services:
  postgres:
    image: postgres:15
    hostname: postgres
    ports: ["5432:5432"]
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: metastore_db
    networks: [trino-network]

  hive-metastore:
    image: bitsondatadev/hive-metastore:latest
    hostname: hive-metastore
    ports: ["9083:9083"]
    volumes:
      - ./metastore_conf/metastore-site.xml:/opt/apache-hive-metastore-3.0.0-bin/conf/metastore-site.xml:ro
    environment:
      METASTORE_DB_HOSTNAME: postgres
      METASTORE_DB_PORT: 5432
      METASTORE_DB_TYPE: postgres
      METASTORE_DB_NAME: metastore_db
      METASTORE_DB_USER: admin
      METASTORE_DB_PASS: admin
    depends_on: [postgres]
    networks: [trino-network]

  minio:
    image: minio/minio:RELEASE.2025-07-18T21-56-31Z
    hostname: minio
    ports: ["9000:9000","9001:9001"]
    volumes:
      - ./minio-data:/data
    environment:
      MINIO_ACCESS_KEY: test
      MINIO_SECRET_KEY: test12334567
    command: server /data --console-address ":9001"
    networks: [trino-network]

  minio-mc:
    image: minio/mc:RELEASE.2025-07-21T05-28-08Z 
    depends_on: [minio]
    entrypoint: >
      /bin/sh -c "
        mc alias set localminio http://minio:9000 test test12334567 &&
        mc mb -p localminio/lakehouse-data || true &&
        echo 'Bucket lakehouse-data ready';
      "
    networks: [trino-network]

  trino:
    image: trinodb/trino:410
    hostname: trino_container
    ports: ["8080:8080"]
    volumes:
      - ./trino/catalog:/etc/trino/catalog
    depends_on: [minio, hive-metastore]
    networks: [trino-network]

volumes:
  trino:
  metastore_conf:
  minio-data:

networks:
  trino-network:
    driver: bridge
