version: '3'
services:

  mariadb:
    image: 'mariadb:latest'
    hostname: mariadb
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: metastore_db
    networks:
      - trino-network

  hive-metastore:
    image: 'bitsondatadev/hive-metastore:latest'
    hostname: hive-metastore
    ports:
      - '9083:9083' # Metastore Thrift
    volumes:
      - ./conf/metastore-site.xml:/opt/apache-hive-metastore-3.0.0-bin/conf/metastore-site.xml:ro
    environment:
      METASTORE_DB_HOSTNAME: mariadb
    depends_on:
      - mariadb
    networks:
      - trino-network

  trino:
    image: trinodb/trino:410
    hostname: trino_container 
    ports:
      - 8080:8080 
    volumes:
      - ./trino/catalog:/etc/trino/catalog
      - ./trino/sql_files:/sql_files
#    command: 
#      bin/bash -c "/usr/lib/trino/bin/run-trino && sleep 60 && trino --file sql_files/create_tables.sql"
    networks:
      - trino-network
    depends_on: 
      - minio 
      - hive-metastore 

  
  minio:
    image: minio/minio:RELEASE.2023-03-24T21-41-23Z
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio-data:/data
    environment:
      MINIO_ACCESS_KEY: test
      MINIO_SECRET_KEY: test12334567
    command: server /data --console-address ":9001"
    networks:
      - trino-network

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 60;
      /usr/bin/mc config host add myminio http://minio:9000 test test12334567;
      /usr/bin/mc mb myminio/sample-lakehouse;
      /usr/bin/mc mb myminio/sample-lakehouse/raw;
      /usr/bin/mc mb myminio/sample-lakehouse/analytics;
      exit 0;
      "



volumes:
  trino:
    driver: local
  conf:
    driver: local
  minio-data:
    driver: local

networks:
  trino-network:
    driver: bridge


#create sql file with commands 
#commit
#create 
#remove hive metastore in favour of jdbc metastore 